version: '3'

output: prefixed

tasks:
  default:
    prefix: "ðŸ“• >"
    desc: "default task"
    cmds:
      - echo "HelloWorld" 

  setup-env:
    prefix: ðŸ > setup-env
    desc: Set up Conda Environment and install dependencies
    cmds:
      - conda create -y -n sphinx -f environment.yaml python=3.9
      - conda activate sphinx
      - pip3 install -r requirements.txt

  build:
    prefix: "ðŸ“• > build"
    desc: Build the Sphinx documentation
    cmds:
      - rm -rf _build
      - sphinx-build docs _build