name: Sphinx-build

on:
  push:
    branches:    
      - master
      - dev

jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
    - with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      run: sphinx-build -b html . _build
