name: Pages
on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    # - uses: actions/setup-python@v2
    # - uses: actions/checkout@master
    #   with:
    #     fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    # - name: Build
    #   run: |
    #     sudo apt install pandoc
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    # - name: Deploy
    #   uses: sphinx-notes/pages@v2
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: gh-pages
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish: true
        requirements_path: ./requirements.txt
        python_version: 3.10
        sphinx_version: 7.2.6
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}}
        cname: docs.geoanalytics.ca